
-- turn off
ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
WITH (STATE = OFF);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SUCCESSFUL_LOGIN_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (LOGOUT_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (LOGOUT_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (AUDIT_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (BACKUP_RESTORE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_OPERATION_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_OWNERSHIP_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_OBJECT_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (DBCC_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (LOGIN_CHANGE_PASSWORD_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (LOGOUT_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SCHEMA_OBJECT_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_OBJECT_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_OPERATION_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_PERMISSION_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_PRINCIPAL_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (SERVER_STATE_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (TRACE_CHANGE_GROUP);

ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
ADD (USER_CHANGE_PASSWORD_GROUP);

-- trun on
ALTER SERVER AUDIT SPECIFICATION STIG_AUDIT_SERVER
WITH (STATE = ON);
